mapFile = 'mapblank.csv'
backgroundImg = "academia2.png"
outputImg = "academia2output.png"
cellNum = 1
pixelSize = 200
mainColor = (255, 255, 255)
lineColor = (0, 0, 0)
csvFlg = False
noCsvXMax = 12
noCsvYMax = 8